# Generated by Django 5.1.2 on 2024-12-09 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0002_availableleave"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availableleave",
            name="encashment_leaves",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="availableleave",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
