# Generated by Django 5.1.2 on 2024-12-10 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0004_alter_availableleave_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availableleave",
            name="available_leaves",
        ),
    ]
