# Generated by Django 5.1.2 on 2024-12-17 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0007_alter_availableleave_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableleave",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_leave",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
