# Generated by Django 5.1.2 on 2024-11-25 10:22

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="designation",
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("quicktech", "Quicktech"),
                            ("quickxom", "Quickxom"),
                            ("quickbound", "Quickbound"),
                        ],
                        max_length=255,
                    ),
                ),
                ("department", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("experienced", "Experienced"),
                            ("senior", "Senior"),
                            ("manager", "Manager"),
                        ],
                        max_length=255,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Hr",
        ),
    ]
