# Generated by Django 5.1.2 on 2024-11-26 08:31

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp",
            field=models.CharField(default=users.models._generate_otp, max_length=6),
        ),
    ]
