# Generated by Django 5.1.2 on 2024-12-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_otp_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_head",
            field=models.BooleanField(default=False),
        ),
    ]
