# Generated by Django 5.1.2 on 2024-12-13 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_remove_organization_users_alter_organization_admin"),
        ("users", "0005_user_organization_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organization.organization",
            ),
        ),
    ]
