# Generated by Django 5.1.2 on 2024-12-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_remove_organization_users_alter_organization_admin"),
        ("users", "0006_user_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="employee",
            name="company",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="joining_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="salary",
        ),
        migrations.AddField(
            model_name="employee",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="organization.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="users.department",
            ),
        ),
    ]
