# Generated by Django 5.1.2 on 2024-12-23 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
    ]
