# Generated by Django 5.1.2 on 2024-12-31 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_remove_organization_users_alter_organization_admin"),
        ("users", "0009_remove_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="organization.organization",
            ),
            preserve_default=False,
        ),
    ]
