# Generated by Django 5.1.2 on 2025-01-01 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_remove_organization_users_alter_organization_admin"),
        ("users", "0010_department_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "organization")},
        ),
    ]
