# Generated by Django 5.1.2 on 2024-12-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave", models.BooleanField(default=True, verbose_name="Leave")),
                (
                    "overtime",
                    models.BooleanField(default=True, verbose_name="Overtime"),
                ),
                ("project", models.BooleanField(default=False, verbose_name="Project")),
                ("review", models.BooleanField(default=False, verbose_name="Review")),
                (
                    "attendence",
                    models.BooleanField(default=False, verbose_name="Attendence"),
                ),
                ("salary", models.BooleanField(default=False, verbose_name="Salary")),
                ("device", models.BooleanField(default=False, verbose_name="Device")),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
