# Generated by Django 5.1.2 on 2024-12-13 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_remove_organization_admins_organization_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="users",
        ),
        migrations.AlterField(
            model_name="organization",
            name="admin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
