# Generated by Django 5.1.2 on 2025-01-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quick_hr", "0005_alter_broadcast_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("verify_email", "Verify Email"),
                    ("registered", "Registered Successfully"),
                    ("pnr_details", "PNR Details"),
                    ("password_reset_done", "Password Reset Done"),
                    ("otp_request", "OTP Request"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
