# Generated by Django 5.1.2 on 2024-11-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("overtime", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="overtime",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overtimes",
                to="project.project",
            ),
        ),
    ]
