# Generated by Django 5.1.2 on 2025-01-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_alter_device_description"),
        ("organization", "0006_remove_organization_users_alter_organization_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="organization.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("title", "organization")},
        ),
    ]
