# Generated by Django 5.1.2 on 2024-11-25 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="review",
            name="description",
        ),
        migrations.RemoveField(
            model_name="review",
            name="title",
        ),
    ]
