# Generated by Django 5.1.2 on 2024-12-11 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_review_options_remove_review_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="month",
            new_name="date",
        ),
    ]
