# Generated by Django 5.1.2 on 2024-12-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_rename_month_review_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="date",
        ),
        migrations.AlterField(
            model_name="review",
            name="created",
            field=models.DateField(),
        ),
    ]
