# Generated by Django 5.1.2 on 2024-12-11 09:20

import review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0005_alter_review_delivery_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews"},
        ),
        migrations.AlterField(
            model_name="review",
            name="created",
            field=models.DateField(default=review.models._review_month_year),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("reviewer", "reviewee", "created")},
        ),
    ]
