# Generated by Django 5.1.2 on 2024-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_alter_review_options_alter_review_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="delivery_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="performance_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="socialization_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                null=True,
            ),
        ),
    ]
