# Generated by Django 5.1.2 on 2024-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0007_alter_review_delivery_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="delivery_rating",
            field=models.IntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="performance_rating",
            field=models.IntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="socialization_rating",
            field=models.IntegerField(
                choices=[
                    (1, "Poor"),
                    (2, "Below Average"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
