# Generated by Django 5.1.2 on 2024-12-24 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0008_alter_review_delivery_rating_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("reviewee", "created")},
        ),
    ]
