# Generated by Django 5.1.2 on 2024-12-17 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_project_slug_task_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="task",
            name="slug",
        ),
    ]
