# Generated by Django 5.1.2 on 2024-12-17 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_remove_project_slug_remove_task_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("title", "project")},
        ),
    ]
