# Generated by Django 5.1.2 on 2024-12-18 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_activity_delete_timesheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_user",
        ),
    ]
