# Generated by Django 5.1.2 on 2024-12-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_remove_task_assigned_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="duration",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
