# Generated by Django 5.1.2 on 2024-12-18 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0013_activity_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created"],
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
    ]
