# Generated by Django 5.1.2 on 2024-12-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_alter_activity_activity_type"),
        (
            "technology",
            "0003_technology_activate_date_technology_deactivate_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="technology.technology"
            ),
        ),
    ]
