# Generated by Django 5.1.2 on 2024-12-24 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={
                "ordering": ["-created"],
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
            },
        ),
    ]
