# Generated by Django 5.1.2 on 2024-12-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("technology", "0002_alter_technology_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
