# Generated by Django 5.1.2 on 2025-01-01 09:37

import django_markdown_model.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "technology",
            "0003_technology_activate_date_technology_deactivate_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="technology",
            name="description",
            field=django_markdown_model.fields.MarkDownField(),
        ),
    ]
