# Generated by Django 5.1.2 on 2024-11-25 16:07

import attendence.models
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("date", models.DateField(default=attendence.models.attendence_data)),
            ],
            options={
                "verbose_name": "attendence",
                "verbose_name_plural": "attendenes",
                "ordering": ["-date"],
            },
        ),
    ]
